#!/usr/bin/env python

import os, sys
import os.path
import subprocess

script_dir = os.path.dirname(os.path.realpath(__file__))
lib_dir = '%s/lib' % script_dir
sys.argv.append("--cm-managed")
if not os.path.isdir(lib_dir):
  print "lib directory is missing.  You must download the entire git repo to run this script"
  print "https://github.com/cmconner156/hue_scripts"
  sys.exit(1)

if not os.environ["USER"] == "root":
  print "This script must be run as root"
  sys.exit(1)

sys.path.insert(0, lib_dir)

from cm_environment import Configurator
hue_bin_dir = Configurator().set_cm_environment()

if not "SKIP_RELOAD" in os.environ.keys():
  Configurator().reload_with_cm_env()

activate_file = hue_bin_dir + "/activate_this.py"
hue_bin = hue_bin_dir + "/hue"

import os; activate_this=os.path.join(os.path.dirname(os.path.realpath(activate_file)), 'activate_this.py'); exec(compile(open(activate_this).read(), activate_this, 'exec'), dict(__file__=activate_this)); del activate_this

with open(hue_bin, 'rU') as f:
  for line in f:
     if "__requires__" in line:
       desktop_ver = line.split("'")

__requires__ = desktop_ver[1]

import sys
from pkg_resources import load_entry_point
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'desktop.settings')

from custom_commands.settings import *
settings.INSTALLED_APPS.append('custom_commands')

if __name__ == '__main__':
    sys.argv.remove("--cm-managed")
    sys.exit(
        load_entry_point('desktop', 'console_scripts', 'hue')()
    )
