#!/usr/bin/env python

import os, sys
import os.path
import subprocess
import logging

script_dir = os.path.dirname(os.path.realpath(__file__))
lib_dir = '%s/lib' % script_dir
#sys.argv.append("--cm-managed")
if not os.path.isdir(lib_dir):
  logging.exception("lib directory is missing.  You must download the entire git repo to run this script")
  logging.exception("https://github.com/cmconner156/hue_scripts")
  sys.exit(1)

if not os.environ["USER"] == "root":
  logging.exception("This script must be run as root")
  sys.exit(1)

sys.path.insert(0, lib_dir)

from cm_environment import set_cm_environment, reload_with_cm_env
hue_config = set_cm_environment()
hue_path = hue_config['hue_path']
hue_bin_dir = hue_config['hue_bin_dir']
HUE_CONF_DIR = hue_config['HUE_CONF_DIR']
parcel_dir = hue_config['parcel_dir']
parcel_name = hue_config['parcel_name']

if not "SKIP_RELOAD" in os.environ.keys():
  reload_with_cm_env()

activate_file = hue_bin_dir + "/activate_this.py"
hue_bin = hue_bin_dir + "/hue"

import os; activate_this=os.path.join(os.path.dirname(os.path.realpath(activate_file)), 'activate_this.py'); exec(compile(open(activate_this).read(), activate_this, 'exec'), dict(__file__=activate_this)); del activate_this

with open(hue_bin, 'rU') as f:
  for line in f:
     if "__requires__" in line:
       desktop_ver = line.split("'")

__requires__ = desktop_ver[1]

import sys
from pkg_resources import load_entry_point
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'desktop.settings')

from custom_commands.settings import *
settings.INSTALLED_APPS.append('custom_commands')

from desktop.conf import DATABASE as desktop_database
logging.info("Using the following config make sure it looks correct")

try:
  import platform
  logging.info("Python Version: %s" % platform.python_version())
  logging.info("OS Version: %s %s" % (platform.linux_distribution()[0], platform.linux_distribution()[1]))
except:
  pass
logging.info("HUE_CONF_DIR: %s" % HUE_CONF_DIR)
logging.info("parcel_dir: %s" % parcel_dir)
logging.info("parcel_name: %s" % parcel_name)
logging.info("hue_bin_dir: %s" % hue_bin_dir)
logging.info("DB Engine: %s" % desktop_database.ENGINE.get())
logging.info("DB Name: %s" % desktop_database.NAME.get())
logging.info("DB User: %s" % desktop_database.USER.get())
logging.info("DB Host: %s" % desktop_database.HOST.get())
logging.info("DB Port: %s" % str(desktop_database.PORT.get()))
if hue_config['LD_LIBRARY_PATH'] is not None:
  logging.inro("LD_LIBRARY_PATH: %s" % hue_config["LD_LIBRARY_PATH"])

if __name__ == '__main__':
#    sys.argv.remove("--cm-managed")
    try:
        sys.exit(
            load_entry_point('desktop', 'console_scripts', 'hue')()
        )
    except UnboundLocalError, e:
        logging.info("Command failed because of bug in older versions of CDH: %s" % e)
        logging.info("Patching and re-running")
        patch_file = "%s/fix_cm_config_file.patch" % script_dir
        patch_cmd = ["patch", "-p1"]
        patch_file_in = open(patch_file)
        os.chdir(hue_path)
        subprocess.call(patch_cmd, stdin=patch_file_in)
        os.chdir(script_dir)
        sys.exit(
            load_entry_point('desktop', 'console_scripts', 'hue')()
        )

