#!/usr/bin/env python

import os, sys
import os.path
import subprocess
import logging
LOG = logging.getLogger(__name__)

script_dir = os.path.dirname(os.path.realpath(__file__))
lib_dir = '%s/lib' % script_dir
sys.argv.append("--cm-managed")
if not os.path.isdir(lib_dir):
  LOG.warn("lib directory is missing.  You must download the entire git repo to run this script")
  LOG.warn("https://github.com/cmconner156/hue_scripts")
  sys.exit(1)

if not os.environ["USER"] == "root":
  LOG.warn("This script must be run as root")
  sys.exit(1)

sys.path.insert(0, lib_dir)

from cm_environment import Configurator
hue_config = Configurator().set_cm_environment()
hue_bin_dir = hue_config['hue_bin_dir']
HUE_CONF_DIR = hue_config['HUE_CONF_DIR']
parcel_dir = hue_config['parcel_dir']
parcel_name = hue_config['parcel_name']

if not "SKIP_RELOAD" in os.environ.keys():
  Configurator().reload_with_cm_env()

activate_file = hue_bin_dir + "/activate_this.py"
hue_bin = hue_bin_dir + "/hue"

import os; activate_this=os.path.join(os.path.dirname(os.path.realpath(activate_file)), 'activate_this.py'); exec(compile(open(activate_this).read(), activate_this, 'exec'), dict(__file__=activate_this)); del activate_this

with open(hue_bin, 'rU') as f:
  for line in f:
     if "__requires__" in line:
       desktop_ver = line.split("'")

__requires__ = desktop_ver[1]

import sys
from pkg_resources import load_entry_point
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'desktop.settings')

from custom_commands.settings import *
settings.INSTALLED_APPS.append('custom_commands')

from desktop.conf import DATABASE as desktop_database
LOG.warn("Using the following config make sure it looks correct")
LOG.warn("HUE_CONF_DIR: %s" % HUE_CONF_DIR)
LOG.warn("parcel_dir: %s" % parcel_dir)
LOG.warn("parcel_name: %s" % parcel_name)
LOG.warn("hue_bin_dir: %s" % hue_bin_dir)
LOG.warn("DB Engine: %s" % desktop_database.ENGINE.get())
LOG.warn("DB Name: %s" % desktop_database.NAME.get())
LOG.warn("DB User: %s" % desktop_database.USER.get())
LOG.warn("DB Host: %s" % desktop_database.HOST.get())
LOG.warn("DB Port: %s" % str(desktop_database.PORT.get())

if __name__ == '__main__':
    sys.argv.remove("--cm-managed")
    sys.exit(
        load_entry_point('desktop', 'console_scripts', 'hue')()
    )
